import { Hero } from './hero';

export const HEROES: Hero[] = [
  { id: 11,
  name: 'Tony Stark',
  quote:'My armor, it was never a distraction or a hobby, it was a cocoon. And now, I\'m a changed man. You can take away my house, all my tricks and toys. But one thing you can\'t take away... I am Iron Man.' , 
  description: 'Anthony Edward "Tony" Stark was a billionaire industrialist, a founding member of the Avengers, and the former CEO of Stark Industries. A brash but brilliant inventor, Stark was self-described as a genius, billionaire, playboy, and philanthropist. With his great wealth and exceptional technical knowledge, Stark was one of the world\'s most powerful men following the deaths of his parents and enjoyed the playboy lifestyle for many years until he was kidnapped by the Ten Rings in Afghanistan, while demonstrating a fleet of Jericho missiles. With his life on the line, Stark created an armored suit which he used to escape his captors. Upon returning home, he utilized several more armors to use against terrorists, as well as Obadiah Stane who turned against Stark. Following his fight against Stane, Stark publicly revealed himself as Iron Man.',
  img:'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/35/IronMan-EndgameProfile.jpg', 
  link:'https://marvelcinematicuniverse.fandom.com/wiki/Iron_Man' 
  },
  { id: 12, 
  name: 'Steve Rogers',
  quote:'For as long as I can remember, I just wanted to do what was right. I guess I\'m not quite sure what that is anymore. And I thought I could throw myself back in and follow orders, serve. It\'s just not the same.' , 
  description: 'Captain Steven Grant "Steve" Rogers is a World War II veteran, a founding member of the Avengers, and Earth\'s first known superhero. Rogers grew up suffering from numerous health problems, and upon America\'s entry into World War II, he was rejected from serving in the United States Army despite several attempts to enlist. Rogers ultimately volunteered for Project Rebirth, where he was the only recipient of the Super Soldier Serum developed by Abraham Erskine under the Strategic Scientific Reserve. The serum greatly enhanced Rogers\' physical abilities to superhuman levels. After Erskine\'s assassination and being doubted by SSR head director Chester Phillips, Rogers was relegated to performing in war bond campaigns, where he posed as a patriotic mascot under the moniker of Captain America.', 
  img:'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/d7/CapAmerica-EndgameProfile.jpg', 
  link:'https://marvelcinematicuniverse.fandom.com/wiki/Steve_Rogers' 
  },
  { id: 13, 
  name: 'Hulk', 
  quote:'I spent a lifetime running from this aspect of myself. Denying half of your being is no way to live, trust me.' ,
  description: 'Doctor Robert Bruce Banner, M.D., Ph.D., is a renowned scientist and a founding member of the Avengers. Highly respected for his work in biochemistry, nuclear physics and gamma radiation, Banner was tasked by Thaddeus Ross to recreate the Super Soldier Serum that created Captain America. However, Ross elected not to inform Banner what he was creating. During the experiment, Banner substituted vita radiation for gamma radiation and administered the serum on himself. As a result, the mild-mannered scientist found that when angered, provoked or excited, his body and brain would transform into a huge, rage-fueled, primitive-minded creature known as the Hulk.', 
  img:'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/79/Hulk_in_the_She-Hulk_series_-_Infobox.jpg', 
  link:'https://marvelcinematicuniverse.fandom.com/wiki/Hulk' 
  },
  { id: 14, 
  name: 'Thor', 
  quote:'This drink, I like it. Another!' ,
  description: 'Thor Odinson is the Asgardian God of Thunder, the former king of Asgard and New Asgard, and a founding member of the Avengers. When his irresponsible and impetuous behavior reignited an ancient war between Asgard and Jotunheim, Thor was denied the right to become king, stripped of his power and hammer Mjølnir, and banished to Earth by Odin. While exiled on Earth, Thor learned humility, finding love with Jane Foster, and helped save his new friends from the Destroyer sent by Loki.',
  img:'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/22/Thor_in_LoveAndThunder_Poster.jpg', 
  link:'https://marvelcinematicuniverse.fandom.com/wiki/Thor' },
  { id: 15, 
  name: 'Black Widow', 
  quote:'I used to have nothing. And then I got this. This job. This family. And I was better because of it. And even though they\'re gone... I\'m still trying to be better.' ,
  description: 'Natalia Alianovna "Natasha" Romanoff was one of the most talented spies and assassins in the entire world and a founding member of the Avengers. As a child, she was indoctrinated into the Red Room by General Dreykov, and briefly lived as the surrogate daughter of Alexei Shostakov and Melina Vostokoff while they were undercover in the United States of America. After the Destruction of the North Institute, she underwent extensive psychological conditioning, before graduating from the Red Room as a Widow. ', 
  img:'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9a/BlackWidow-EndgameProfile.jpg', 
  link:'https://marvelcinematicuniverse.fandom.com/wiki/Black_Widow' },
  { id: 16, 
  name: 'Hawkeye', 
  quote:'Okay, look, the city is flying, we\'re fighting an army of robots... and I have a bow and arrow. None of this makes sense. But I\'m going back out there because it\'s my job.' ,
  description: 'Clinton Francis "Clint" Barton is an extremely skilled marksman, a former special agent of S.H.I.E.L.D. and one of the founding members of the Avengers. Known for his use of the bow and arrow as his primary weapon and an extremely keen eyesight and accuracy that earned him the codename Hawkeye, Barton had become one of the best S.H.I.E.L.D. agents, responsible for the recruitment of Black Widow, whom he developed a strong friendship with. Assigned by Nick Fury into watching over the Tesseract, he was brainwashed by Loki and used as his pawn in his attempt to become king of Midgard. However, following their Attack on the Helicarrier, he was freed from Loki\'s mental controls by Black Widow and joined the Avengers to fight against Loki and the Chitauri army in the battle of New York, ending Loki\'s invasion, before Hawkeye had returned to his work at a S.H.I.E.L.D..', 
  img:'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/f/f5/Hawkeye_Char_Poster.jpg', 
  link:'https://marvelcinematicuniverse.fandom.com/wiki/Hawkeye' },
  { id: 17,
  name: 'Loki', 
  quote:'I, Loki, Prince of Asgard, Odinson, the rightful King of Jotunheim, God of Mischief, do hereby pledge to you, my undying fidelity' ,
  description: 'Loki Laufeyson was the biological son of Laufey, the ruler of the Frost Giants in Jotunheim, who was abandoned and left to die shortly after his birth. Found by Odin, Loki was taken to Asgard and raised by him and Frigga as an Asgardian prince, along with Thor. When Thor was to be crowned King, Loki had sabotaged the coronation by letting the Frost Giants attack Asgard, thus leading Thor to seek vengeance on Jotunheim, which resulted in Thor\'s banishment to Earth and Loki finding out the truth about his heritage. Frigga gave Loki the throne when Odin had fallen into the Odinsleep; however, when the Warriors Three and Sif attempted to return Thor home, Loki was forced to try to stop them. Regardless, Thor returned from his exile on Earth and ended Loki\'s reign, thwarting his attempt to declare war on the Nine Realms with Jotunheim\'s destruction. With Odin disapproving of his actions, Loki allowed himself to fall through the deep abyss of space, entering a wormhole created by the sudden termination of the Bifrost Bridge.', 
  img:'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/7d/Thor_Ragnarok_Textless_Character_Posters_03.jpg', 
  link:'https://marvelcinematicuniverse.fandom.com/wiki/Loki' },
  { id: 18,
  name: 'Spider-Man', 
  quote:'I really did try to help you. I mean, I could\'ve killed you. At any given moment, but I didn\'t. Because my Aunt May taught me that everyone deserves a second chance.' ,
  description: 'Peter Benjamin Parker is a former high school student who gained spider-like abilities, fighting crime across New York City as the superhero Spider-Man. While Parker juggled all his continued hero duties with the demands of his high-school life, he was approached by Tony Stark who recruited Spider-Man to join the Avengers Civil War, putting Spider-Man into the brief conflict with his personal hero, Captain America. Parker was given a new suit as well as new Stark technology in exchange for his help, allowing him to return back home to continue his own hero work.', 
  img:'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/48/Spider-Man_No_Way_Home_poster_011_Textless.jpg', 
  link:'https://marvelcinematicuniverse.fandom.com/wiki/Spider-Man' 
  },
  { id: 19,
  name: 'Captain Marvel',
  quote:'I\'m coming to end it. The war, the lies, all of it.' ,
  description: 'Carol Susan Jane Danvers is a former United States Air Force pilot who, upon being exposed to the energy of the Tesseract via the destruction of the Light-Speed Engine, obtained cosmic powers. She gained further powers when she was made into a Kree-human hybrid via a blood transfusion from Yon-Rogg, and had all of her old memories removed, turning her into the Kree\'s weapon and a member of Starforce. Now operating as Vers, she was captured by Skrulls during the Kree-Skrull War, resulting in her returning to Earth and beginning to recall her past, with help from Nick Fury and Maria Rambeau. Vers subsequently discovered that Yon-Rogg and the Kree Empire had been manipulating her for years, learning from Talos that the Skrulls were merely seeking to find a new home. With this information, Danvers, rejecting her Vers persona, unlocked her true powers and defeated the Kree invasion onto Earth that was being led by Ronan the Accuser, before setting off out to the far reaches of the galaxy to finish what her late mentor Mar-Vell had previously started, honoring her by becoming known as Captain Marvel.', 
  img:'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/f/fe/CapMarvel-EndgameProfile.jpeg', 
  link:'https://marvelcinematicuniverse.fandom.com/wiki/Captain_Marvel' 
  },
  { id: 20,
  name: 'Okoye',
  quote:'I am loyal to that throne. No matter who sits upon it.', 
  description: 'Okoye is the General of the Dora Milaje and the head of Wakandan armed forces and intel. Witnessing T\'Challa\'s coronation, she joins him in tracking down Ulysses Klaue. After Erik Killmonger overthrew T\'Challa, Okoye found herself conflicted between her friendship with T\'Challa, or her duty to her new king. T\'Challa soon returned and Okoye soon joined him in the fight against Killmonger and successfully taking back the throne.', 
  img:'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/56/Okoye-EndgameProfile.jpeg', 
  link:'https://marvelcinematicuniverse.fandom.com/wiki/Okoye' 
  },
  { id: 21,
  name: 'Ant-Man', 
  quote:'Why don\'t you pick on someone your own size?',
  description: 'Scott Edward Harris Lang is a former convicted thief who was struggling to pay child support to his estranged wife for visitation rights to his daughter, Cassie Lang. With the promise of money, he was convinced by Hank Pym to take on the mantle of Ant-Man: a superhero with an advanced suit designed to shrink its wearer to a tiny size while increasing one\'s toughness, agility, and physical strength. Trained under both Pym and his daughter Hope van Dyne, Ant-Man was to help foil Pym\'s former protege Darren Cross, who was intending to sell his Yellowjacket Suit design and his copy of the Pym Particles formula to HYDRA and the Ten Rings. However, their plan was discovered by Cross, culminating in a final fight between Yellowjacket and Ant-Man. To defeat Yellowjacket, Ant-Man had to shrink small enough to enter Yellowjacket\'s suit and destroy it, sending Ant-Man to the Quantum Realm, but Ant-Man was able to escape. Ant-Man\'s heroism helped restore his relationship with Cassie and his ex-wife, as well as find a new romantic one with van Dyne. Lang soon learned that the Avengers were seeking to recruit him.', 
  img:'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/e/ea/AntMan-EndgameProfile.jpg', 
  link:'https://marvelcinematicuniverse.fandom.com/wiki/Ant-Man' },
  
];